# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb47001ef9a9fa25a19cfde01ef853fa7bcfa9c16941a60f4c8828e4de359855a856051c9b0b293bc5677ad755d2e52b185b8cc9a035b13d04ecfcfade6ebe50

test:
  secret_key_base: 54799b662bac215e7b845af6fb27f0e53295f655d3d52d27f927893814e7423b2721893bcaffcbcaf18a61409a0e92864575a2962ecf522d3123d9c754abf30d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
